### ISSUE TITLE
Possibility to align elements vertically

### ISSUE THREAD

**Issue by rewop** [jackmcpickle/flex_e_ble#1]
I noticed that grid elements cannot be aligned vertically, but they always stretch the to the height of the parent container by default.

It would be interesting to add classes to also align vertically, with the `align-items` and `self-align` properties. 

Does it make sense?

**Comment by jackmcpickle** [comment]
Feel free to add a PR. I will look into in a few days.

**Comment by jackmcpickle** [comment]
@rewop what do you think of my PR to address this? Note that stretch is the default setting of flex items.

**Comment by rewop** [comment]
@jackmcpickle Great! I just came back from holiday. Tonight I will try it out.
